# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json' ], fallback_format: json }
            - { path: '^/', priorities: [ 'text/html', '*/*' ], fallback_format: html }

    exception:
        enabled: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.