nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: [ 'POST', 'OPTIONS', 'PUT', 'GET', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization', 'X-Custom-Auth', 'X-Custom-Header', 'origin', 'accept', 'bearer' ]
    expose_headers: ['link']
    max_age: 36000
  paths:
    '^/': ~